services:
  app:
    build: ./sbm-manager
    container_name: sbm_manager
    ports:
      - '8080:8080'
    volumes:
      - ./sbm-manager:/app
      - /app/node_modules
    command: yarn serve
    networks:
      - sbm-network
    env_file:
      - ./.env
    environment:
      - VUE_APP_API_URL=${VUE_APP_API_URL}
      - VUE_APP_SBM_API_URL=${VUE_APP_SBM_API_URL}
      - VUE_APP_DP_API_URL=${VUE_APP_DP_API_URL}
      - VUE_APP_API_USERNAME=${VUE_APP_API_USERNAME}
      - VUE_APP_API_PASSWORD=${VUE_APP_API_PASSWORD}

networks:
  sbm-network:
    external: true
