services:
  app:
    build: ./sbm-manager
    container_name: sbm_manager
    ports:
      - '8200:8080'
    volumes:
      - ./sbm-manager:/app
      - /app/node_modules
    command: yarn serve
    networks:
      - sbm-network
    env_file:
      - ./.env.dev

networks:
  sbm-network:
    external: true