sonar.projectKey=SBM-MANAGER
sonar.projectName=SBM-MANAGER
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

sonar.sources=sbm-manager/src/api/clients.js,sbm-manager/src/views/ProductView.vue,sbm-manager/src/components/CRUDManagerComponent.vue,sbm-manager/src/components/CRUDGridComponent.vue,sbm-manager/src/components/SimpleFormComponent.vue,sbm-manager/src/components/PropertiesComponent.vue,sbm-manager/src/components/ConfirmComponent.vue
sonar.tests=sbm-manager/src
sonar.test.inclusions=**/__tests__/**/*.spec.js

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/assets/**,**/*.spec.js
sonar.coverage.exclusions=**/__tests__/**,**/*.spec.js
sonar.javascript.lcov.reportPaths=sbm-manager/coverage/lcov.info
sonar.typescript.tsconfigPaths=sbm-manager/tsconfig.sonar.json
sonar.javascript.createTSProgramForOrphanFiles=false
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
